### ISSUE TITLE
Flow lib export is broken

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/brewskey.js-api#25]
when we use the lib in other project. import types { someType } works correct. but DAOApi.createFilter() -or whatever from DAOApi is not typechecked. 
I need to figure out correct way to export default from flow module declarations.
there are some work around here:
https://github.com/facebook/flow/issues/1806
I tried this:
declare type DAOApi = {
 createFilter: ...
...,
}
declare export default DAOApi;

but seems this doesn't work :/

**Comment by AntonPuko** [comment]
actually other types not typechecked in brewskey.admin, either :/

**Comment by jlkalberer** [comment]
Yeah.. typecheck doesn't work very well :/
